// Server-side consent template for PDF generation
// Mirrors client/src/constants/consentTemplate.js — English, French, Kinyarwanda

export const CONSENT_TEMPLATE = {
  en: {
    title: 'Informed Consent Form',
    studyTitle: 'Study Title: Characterization of Omics Perturbations Driving Leukemia in the Rwandan Population',
    sections: [
      { heading: 'Introduction and Voluntary Consent', body: 'Good morning,\n\nI am Esperance UMUMARARUNGU, the Director of the Molecular and Genomics Unit at the National Reference Laboratory in Rwanda. I am collaborating with researchers from the University of Rwanda and the University of Liège in Belgium on a study focusing on the characterization of omics perturbations driving leukemia in the Rwandan population.\n\nThe purpose of this research is to identify key genetic, epigenetic, and molecular changes involved in leukemia development in Rwanda. By understanding the biological mechanisms behind this disease, we aim to improve diagnosis and treatment strategies.\n\nYou have been invited to participate in this study due to its significance in enhancing health outcomes in Rwanda. The study has received authorization from the Ethics Committee of the College of Medicine and Health Sciences and the CHUK Ethical Committee. Your participation is voluntary, and you can choose not to participate or withdraw at any time without consequences for you or your family. We will provide you with all necessary information to help you make an informed decision.' },
      { heading: 'A. Purpose of the Research', body: 'The aim of this research is to characterize the molecular and genomic changes associated with leukemia among the Rwandan population. Through genomic and epigenomic analyses, we hope to gain insights into the disease and its potential drivers, which will enable the development of personalized treatment approaches.' },
      { heading: 'B. Selection for participation/of participants', body: 'You have been invited because you are a leukemia patient in Rwanda. Your participation will contribute to a better understanding of the genetic drivers of leukemia, which could lead to improved diagnostics and treatments. Please take your time to decide, and feel free to discuss this with family or friends. Your participation is voluntary, and your privacy will be strictly protected.' },
      { heading: 'C. Contribution/Role of a participant to the Research', body: 'If you choose to participate, we will collect the following:\n• A blood sample (10 ml)\n• A bone marrow sample, if applicable, as part of your routine medical care\n• Clinical information about your leukemia diagnosis and treatment history\n\nYour samples will be anonymized to ensure that you cannot be personally identified. Some tests will be conducted in Rwanda, while others may be performed in collaboration with partner institutions abroad.' },
      { heading: 'D. Samples and Data use and protection', body: 'Your samples will be analyzed to study genetic mutations and changes in gene expression associated with leukemia. These analyses will help identify potential biomarkers for diagnosis and treatment. The data will be used for this research and may be shared with other researchers globally under strict regulations. We ensure that your data will be anonymized and only accessible to the research team. It will not be shared with unauthorized persons or used for other purposes without your explicit consent. Your data will not be sold or used for profit.' },
      { heading: 'E. Duration of the Research', body: 'Your direct participation involves providing the required samples and information. However, the analysis of your DNA and data may continue for several years as part of ongoing research efforts. Your data and samples may also be used in future research studies.' },
      { heading: 'F. Benefits of Participation', body: 'While there is no direct benefit to you, your participation will contribute to the global understanding of leukemia and may help future patients receive better care and treatment.' },
      { heading: 'G. Risks Involved', body: 'There are minimal risks associated with this research. Blood and bone marrow sample collection may cause discomfort or bruising at the site, but precautions will be taken to minimize these risks.' },
      { heading: 'I. Voluntary Participation', body: 'Your participation is entirely voluntary. You may withdraw at any time without explanation or consequences. You do not need to answer any questions you are uncomfortable with, and you can stop participating at any time.' },
      { heading: 'J. Result Dissemination', body: 'You will receive a summary of the overall study results, which will reflect findings for all participants, not individual results. If any significant findings related to your health are discovered, we will contact you to inform you, provided you express an interest in receiving such information.' },
      { heading: 'K. Participation Compensation', body: 'Participants will not receive direct financial compensation, but transport costs will be reimbursed, and you will receive a small sum of 5,000 RWF for your time.' },
      { heading: 'L. Contact for Further Information', body: 'For any questions regarding this study, please contact:\n• Esperance UMUMARARUNGU: (+250) 788287222\n• Prof. Florence Masaisa, Hematologist at CHUK: (+250) 788650009' },
    ],
    consentStatement: 'I have been provided all the required information and I understand my role in this study. I understand that I can withdraw from this study at any time without consequences. I consent to participate in this study.',
    consentSectionLabel: 'Consent Form',
    participantLabel: 'Name of the participant',
    researcherLabel: 'Name of the researcher',
    signatureAndDate: 'Signature and Date',
    doneAt: 'Done at',
  },

  fr: {
    title: 'Formulaire de consentement éclairé',
    studyTitle: 'Étude : Caractérisation des perturbations omiques à l’origine de la leucémie dans la population rwandaise',
    sections: [
      { heading: 'Introduction et consentement volontaire', body: 'Bonjour,\n\nJe suis Esperance UMUMARARUNGU, Directrice de l’Unité de Biologie Moléculaire et Génomique au Laboratoire National de Référence du Rwanda. Je collabore avec des chercheurs de l’Université du Rwanda et de l’Université de Liège en Belgique sur une étude portant sur la caractérisation des perturbations omiques à l’origine de la leucémie dans la population rwandaise.\n\nL’objectif de cette recherche est d’identifier les changements génétiques, épigénétiques et moléculaires clés impliqués dans le développement de la leucémie au Rwanda. En comprenant les mécanismes biologiques de cette maladie, nous espérons améliorer les stratégies de diagnostic et de traitement.\n\nVous êtes invité(e) à participer à cette étude en raison de son importance pour l’amélioration des résultats de santé au Rwanda. L’étude a reçu l’autorisation du Comité d’Éthique du Collège de Médecine et des Sciences de la Santé et du Comité d’Éthique du CHUK. Votre participation est volontaire et vous pouvez choisir de ne pas participer ou de vous retirer à tout moment sans conséquence pour vous ou votre famille.' },
      { heading: 'A. Objectif de la recherche', body: 'Cette recherche vise à caractériser les changements moléculaires et génomiques associés à la leucémie dans la population rwandaise. Grâce à des analyses génomiques et épigénomiques, nous espérons mieux comprendre la maladie et ses facteurs déclenchants potentiels, ce qui permettra de développer des approches thérapeutiques personnalisées.' },
      { heading: 'B. Sélection des participants', body: 'Vous avez été invité(e) car vous êtes un(e) patient(e) atteint(e) de leucémie au Rwanda. Votre participation contribuera à une meilleure compréhension des facteurs génétiques de la leucémie, ce qui pourrait améliorer les diagnostics et les traitements.' },
      { heading: 'C. Rôle du participant dans la recherche', body: 'Si vous choisissez de participer, nous collecterons :\n• Un échantillon sanguin (10 ml)\n• Un échantillon de moelle osseuse, le cas échéant\n• Des informations cliniques sur votre diagnostic\n\nVos échantillons seront anonymisés afin que vous ne puissiez pas être identifié(e) personnellement.' },
      { heading: 'D. Utilisation et protection des échantillons et données', body: 'Vos échantillons seront analysés pour étudier les mutations génétiques et les modifications de l’expression génique associées à la leucémie. Vos données ne seront pas vendues ni utilisées à des fins lucratives.' },
      { heading: 'E. Durée de la recherche', body: 'Votre participation directe consiste à fournir les échantillons et informations requis. Toutefois, l’analyse de votre ADN et de vos données peut se poursuivre pendant plusieurs années.' },
      { heading: 'F. Bénéfices de la participation', body: 'Bien qu’il n’y ait pas de bénéfice direct pour vous, votre participation contribuera à la compréhension globale de la leucémie.' },
      { heading: 'G. Risques encourus', body: 'Les risques associés à cette recherche sont minimes. Le prélèvement d’échantillons sanguins et de moelle osseuse peut provoquer un inconfort ou des ecchymoses au site de prélèvement.' },
      { heading: 'I. Participation volontaire', body: 'Votre participation est entièrement volontaire. Vous pouvez vous retirer à tout moment sans explication ni conséquence.' },
      { heading: 'J. Diffusion des résultats', body: 'Vous recevrez un résumé des résultats globaux de l’étude. Si des résultats significatifs liés à votre santé sont découverts, nous vous contacterons.' },
      { heading: 'K. Compensation de la participation', body: 'Les participants ne recevront pas de compensation financière directe, mais les frais de transport seront remboursés, et vous recevrez une petite somme de 5 000 RWF pour votre temps.' },
      { heading: 'L. Contact pour informations complémentaires', body: 'Pour toute question concernant cette étude, veuillez contacter :\n• Esperance UMUMARARUNGU : (+250) 788287222\n• Pr. Florence Masaisa, Hématologue au CHUK : (+250) 788650009' },
    ],
    consentStatement: 'J’ai reçu toutes les informations requises et je comprends mon rôle dans cette étude. Je comprends que je peux me retirer de cette étude à tout moment sans conséquence. Je consens à participer à cette étude.',
    consentSectionLabel: 'Formulaire de consentement',
    participantLabel: 'Nom du participant',
    researcherLabel: 'Nom du chercheur',
    signatureAndDate: 'Signature et date',
    doneAt: 'Fait à',
  },

  ki: {
    title: 'Urupapuro rwo kwemera kugira uruhare mu bushakashatsi',
    studyTitle: 'Izina Ry’ubushakashatsi: Isesengura ry’ihindagurika muturemangingo zitera kanseri y’amaraso (leukemia) mu baturage b’u Rwanda',
    sections: [
      { heading: 'Intangiriro, amakuru ya ngombwan’uburenganzira bwo kwemera cyangwa kwanga kwitabira', body: 'Muraho neza,\n\nNitwa Esperance UMUMARARUNGU, Umuyobozi w’Ishami rishinzwe ipimwa ry“uturemangingo muri Laboratwari nkuru y’Igihugu (National Reference Laboratory) ibarizwa mu Kigo cy’Igihugu gishizwe Ubuzima (Rwanda Biomedical Center).\n\nUbushakashatsi bwacu bufite intego yo kumenya neza impinduka zitera kanseri y’amaraso (leukemia) mu baturage b’u Rwanda. Nkorana n’abashakashatsi b’Abanyarwanda, barimo abo muri Kaminuza y’u Rwanda, ndetse n’abashakashatsi b’Ababiligi bo muri Kaminuza ya Liège.\n\nUbushakashatsi bwacu bugamije kumenya neza impinduka zitera iyi ndwara kugira ngo dushobore kunoza uburyo bwo kuyipima no kuyivura.\n\nWahiswemo kugira uruhare muri ubu bushakashatsi kuko byitezwe ko buzagira ingaruka nziza ku buzima bw’abaturage b’u Rwanda. Ubushakashatsi bwemejwe na Komite y’Ubuvuzi n’Ubuzima ya Koleji ya Medicine na Komite y’Ubuvuzi ya CHUK. Kwitabira si itegeko, kandi ushobora guhitamo kutitabira cyangwa ukava mu bushakashatsi igihe ari cyo cyose nta ngaruka bikugizeho cyangwa bigize ku muryango wawe.' },
      { heading: 'A. Intego y’ubu bushakashatsi', body: 'Intego y’ubu bushakashatsi ni kumenya impinduka zishobora guteza kanseri y’amaraso (leukemia) mu baturage b’u Rwanda. Tuzakora isesengura ry’uturemangingo kugira ngo tumenye imvano nyakuri y’iyi ndwara, kandi ibyo bizadufasha mu gushaka uburyo bwihariye bwo kuvura abarwayi kugira ngo bagire imibereho myiza.' },
      { heading: 'B. Guhitamo uwitabira ubu bushakashatsi', body: 'Wahiswemo kwitabira kuko uri muri bamwe bafite kanseri y’amaraso mu Rwanda. Uruhare rwawe ruzadufasha kumenya impamvu zitera kanseri, bizanadufasha kuvura no gupima neza iyi ndwara.' },
      { heading: 'C. Urahare muri ubu bushakashatsi', body: 'Niwemera kwitabira, hazakusanywa ibi bikurikira:\n• Gufatwa amaraso (mililitiro 10)\n• Gufatwa ikizaminin cyo mumusokoro niba ari ngombwa\n• Amakuru yerekeye ubuvuzi bwawe\n\nIbizamini byawe bizagirwa ibanga, ku buryo nta muntu uzabasha kukumenya.' },
      { heading: 'D. Akamaro k’ibizamini n’amakuru yawe n’umutekano wabyo.', body: 'Ibizamini byawe bizasuzumwa kugira ngo hasuzumwe uturema ngingo dufitanye isano na kanseri y’amaraso. Nta makuru yawe azagurishwa cyangwa akoreshwe ku nyungu bwite.' },
      { heading: 'E. Igihe bushakashatsi buzamara', body: 'Isesengura ry’ADN n’amakuru yawe rizakomeza igihe kirekire mu rwego rw’ubushakashatsi buhoraho.' },
      { heading: 'F. Akamaro ko kwitabira ubu bushakashatsi', body: 'Ntabwo hari inyungu z’umuntu ku giti cye, ariko uruhare rwawe ruzafasha kumenya neza iby’iyi ndwara ya kanseri y’amaraso.' },
      { heading: 'G. Impungenge zagaragara muri ubu bushakashatsi', body: 'Hari ibyago bike cyane. Gufata amaraso cyangwa gufata ikizami mu musokoro, bishobora gutera kubabara ahafashwe ikizamini.' },
      { heading: 'I. Kwitabira ubushakashatsi', body: 'Kwitabira ni ubushake bwawe kandi ushobora guhagara igihe icyo ari cyo cyose ubyifuje kandi nta ngaruka uzagira.' },
      { heading: 'J. Ibijyanye n’amakuru y’ibizava muri ubu bushakashatsi', body: 'Uzahabwa ishusho rusange y’ibizava muri ubu bushakashatsi.' },
      { heading: 'K. Ibihembo mukwitabira ubu bushakashatsi', body: 'Nta gihembo cy’amafaranga kizahabwa, ariko uzishyurwa amafaranga y’ingendo, kandi uzahabwa amafaranga ibihumbi bitanu (5,000 RWF) kubw’igihe cyawe.' },
      { heading: 'L. Abo wakwegera kugira ngo ukeneye andi makuru', body: 'Kubibazo bijyanye n’ubu bushakashatsi, wahamagara:\n• Esperance UMUMARARUNGU: (+250) 788287222\n• Prof. Florence Masaisa, umuganga w’indwara z’amaraso muri CHUK: (+250) 788650009' },
    ],
    consentStatement: 'Nahawe amakuru ahagiye n’umva uruhare rwanjye muri ubu bushakashatsi. Ndasobanukiwe ko nshobora gukuramo uruhare rwanjye igihe icyo ari cyo cyose nta ngaruka. Nemeye kwitabira ubu bushakashatsi.',
    consentSectionLabel: 'Ifishi yo kwemera no kwitabira ubushakashatsi',
    participantLabel: 'Izina ry’uwitabiriye',
    researcherLabel: 'Izina ry’umushakashatsi',
    signatureAndDate: 'Igikono n’Itariki',
    doneAt: 'Byakozwe kuri',
  },
};
