import { SITES } from './index.js';

export const DEF_USERS = [
  {
    id: 'u_esp',
    name: 'Esperance Umumararungu',
    username: 'esperance',
    password: 'leuktrack2025',
    role: 'admin',
    sites: [...SITES],
    isDefault: true,
    createdAt: '2025-01-01T00:00:00Z',
    createdBy: 'system',
  },
  {
    id: 'u_sup',
    name: 'Supervisor Rwanda',
    username: 'supervisor',
    password: 'viewer2025',
    role: 'viewer',
    sites: [...SITES],
    isDefault: true,
    createdAt: '2025-01-01T00:00:00Z',
    createdBy: 'system',
  },
  {
    id: 'u_lie',
    name: 'Liège Team',
    username: 'liege_user',
    password: 'liege2025',
    role: 'liege',
    sites: [...SITES],
    isDefault: true,
    createdAt: '2025-01-01T00:00:00Z',
    createdBy: 'system',
  },
];

export const SEED_PATIENTS = [
  {
    id: 'p1',
    code: '001',
    name: 'GASANA Claude',
    age: 48,
    leukemiaType: 'AML',
    treatment: 'On Treatment',
    facility: 'RMH',
    enrolledAt: '2025-01-10T09:00:00Z',
    enrolledBy: 'u_esp',
    updatedAt: '2025-01-10T09:00:00Z',
    updatedBy: 'u_esp',
  },
  {
    id: 'p2',
    code: '002',
    name: 'Nsengiyumva Schadrack',
    age: 46,
    leukemiaType: 'AML',
    treatment: 'Not on Treatment',
    facility: 'KFH',
    enrolledAt: '2025-01-12T10:00:00Z',
    enrolledBy: 'u_esp',
    updatedAt: '2025-01-12T10:00:00Z',
    updatedBy: 'u_esp',
  },
  {
    id: 'p3',
    code: '003',
    name: 'Uzaribara Ignace',
    age: 61,
    leukemiaType: 'CLL',
    treatment: 'Not on Treatment',
    facility: 'RMH',
    enrolledAt: '2025-01-15T11:00:00Z',
    enrolledBy: 'u_esp',
    updatedAt: '2025-01-15T11:00:00Z',
    updatedBy: 'u_esp',
  },
  {
    id: 'p4',
    code: '004',
    name: 'Ruzagiriza Cyriac',
    age: 87,
    leukemiaType: 'AML',
    treatment: 'Not on Treatment',
    facility: 'RMH',
    enrolledAt: '2025-01-18T08:00:00Z',
    enrolledBy: 'u_esp',
    updatedAt: '2025-01-18T08:00:00Z',
    updatedBy: 'u_esp',
  },
];
